# http://www.appveyor.com/docs/appveyor-yml

# version format
version: 0.1.{build}

environment:
  package_dir: NuGet_Packages

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: "**\\AssemblyInfo.*"
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, AnyCPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

before_build:
  - ps: If (Test-Path "$env:package_dir") { Remove-Item "$env:package_dir" -Recurse -Force -ErrorAction SilentlyContinue }
  - nuget restore src\mona.sln  
  
build:
  project: src/Mona.sln
  
  # MSBuild verbosity level(quiet|minimal|normal|detailed)
  verbosity: minimal

# scripts to run after build
after_build:
  - mkdir %PACKAGE_DIR%
  #build a symbols package
  - nuget pack src\Mona\Mona.nuspec -OutputDirectory %PACKAGE_DIR% -BasePath src\Mona -Verbosity Detailed -Version %APPVEYOR_BUILD_VERSION% -Symbols -Properties Configuration=Release

artifacts:
  # pushing all *.nupkg files in directory
  - path: 'NuGet_Packages\*.nupkg'
  
deploy:
  on:
    branch: master
    platform: Any CPU
  provider: NuGet
  api_key:
    secure: ziVo0NrHo/STAKb5ItXNh5cOqJqtkVvZl2nHL8E/OFsjQ3TfUwcC0bkeK4mpJmGl
