# http://www.appveyor.com/docs/appveyor-yml

# version format
version: 0.1.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: "**\AssemblyInfo.*"
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, AnyCPU. This setting is optional.
platform: AnyCPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  project: src/Mona.sln
  publish_nuget: true
  
  # MSBuild verbosity level(quiet|minimal|normal|detailed)
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: ziVo0NrHo/STAKb5ItXNh5cOqJqtkVvZl2nHL8E/OFsjQ3TfUwcC0bkeK4mpJmGl
