//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mona {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mona.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} sequence..
        /// </summary>
        internal static string ErrorSequenceFormat {
            get {
                return ResourceManager.GetString("ErrorSequenceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} sequence that {1}..
        /// </summary>
        internal static string ErrorSequencePredicateFormat {
            get {
                return ResourceManager.GetString("ErrorSequencePredicateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a single {0}..
        /// </summary>
        internal static string ErrorSingleFormat {
            get {
                return ResourceManager.GetString("ErrorSingleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a single {0} that {1}..
        /// </summary>
        internal static string ErrorSinglePredicateFormat {
            get {
                return ResourceManager.GetString("ErrorSinglePredicateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorStringFormat {
            get {
                return ResourceManager.GetString("ErrorStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} sequence..
        /// </summary>
        internal static string ErrorWhileFormat {
            get {
                return ResourceManager.GetString("ErrorWhileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} sequence that {1}..
        /// </summary>
        internal static string ErrorWhilePredicateFormat {
            get {
                return ResourceManager.GetString("ErrorWhilePredicateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matched an unspecified predicate.
        /// </summary>
        internal static string PredicateUnspecified {
            get {
                return ResourceManager.GetString("PredicateUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was &quot;{0}&quot;.
        /// </summary>
        internal static string PredicateWasLiterallyFormat {
            get {
                return ResourceManager.GetString("PredicateWasLiterallyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to character.
        /// </summary>
        internal static string SymbolTypeCharacter {
            get {
                return ResourceManager.GetString("SymbolTypeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol.
        /// </summary>
        internal static string SymbolTypeSymbol {
            get {
                return ResourceManager.GetString("SymbolTypeSymbol", resourceCulture);
            }
        }
    }
}
